```
pip install numpy
```

In [ ]:
import numpy as np

In [ ]:
n1 = np.array([1,2,3,4])
print(n1)
print(type(n1))

In [ ]:
n1.shape

In [ ]:
n2 = np.array([[1,2,3],[2,3,5]])
print(n2)
print(n2.shape)

creating matrix
- arange
- linspace
- random.rand
- random.randn
- random.randint
- eye
- ones
- zeros

In [ ]:
x = np.arange(-10, 10, .2)
x.shape

In [ ]:
y = np.linspace(1, 5, 25)
print(y)

In [ ]:
np.random.rand(3,3)

In [ ]:
np.random.randn(10)

In [ ]:
np.random.randint(1, 5, (5,5))

In [ ]:
x = np.random.randint(1,10, (3,2))
y = np.random.randint(1,10, (3,2))
print(x)
print(y)

In [ ]:
x + 5

In [ ]:
x + y

In [ ]:
x * y

In [ ]:
x.T

In [ ]:
x.dot(y.T)

In [ ]:
np.sin(x)

In [ ]:
print(x.sum())
print(x.mean())
print(x.std())

In [ ]:
a = np.linspace(0, 5, 50)
print(a.shape)
a2 = a.reshape(10, 5)
print(a2)
print(a2.shape)

In [ ]:
a2.reshape(50)

In [ ]:
m = np.random.randint(1, 10, (10, 10))
print(m)

In [ ]:
print(m[0, 0]) # first row, first column
print(m[0, -1]) # first row, last column
print(m[-1,0]) # last row, first column
print(m[-1,-1])  # last row, last column

In [ ]:
print(m[0]) # first row
print(m[1]) # second row
print(m[-1]) # last row
print(m[:3]) # first 3 rows
print(m[-3:]) # last 3 rows

In [ ]:
print(m[:,0]) # 1st column
print(m[:,-1]) # last column
print(m[:, :3]) # first 3 column
print(m[:, -3:]) # last 3 column

In [ ]:
print(m[:, [0,2,3,5]])

filtering

In [ ]:
m < 5 # boolean filter

In [42]:
m[m<5]

array([2, 3, 2, 1, 3, 2, 4, 4, 4, 1, 1, 1, 4, 1, 1, 3, 2, 2, 1, 3, 1, 4,
       2, 3, 4, 2, 1, 2, 1, 1, 2, 2, 1, 3, 3, 4, 2, 1, 3, 4, 2, 4, 3, 3])

In [49]:
m[m>3]

array([6, 7, 9, 5, 6, 9, 8, 4, 9, 9, 4, 5, 4, 4, 7, 9, 5, 7, 8, 6, 6, 7,
       5, 6, 9, 8, 8, 9, 5, 9, 5, 9, 4, 9, 4, 7, 7, 5, 9, 9, 9, 5, 7, 9,
       9, 6, 6, 7, 7, 8, 4, 9, 6, 8, 4, 5, 8, 4, 9, 8, 6, 6, 9, 6, 5])

In [46]:
m[(m >= 3) & (m <= 6)]

array([6, 3, 5, 6, 3, 4, 4, 5, 4, 4, 5, 3, 6, 6, 5, 6, 5, 5, 3, 4, 3, 4,
       5, 5, 6, 3, 6, 3, 4, 6, 3, 4, 5, 4, 3, 6, 6, 6, 5, 3])

In [47]:
m.flatten?

Docstring:
a.flatten(order='C')

Return a copy of the array collapsed into one dimension.

Parameters
----------
order : {'C', 'F', 'A', 'K'}, optional
    'C' means to flatten in row-major (C-style) order.
    'F' means to flatten in column-major (Fortran-
    style) order. 'A' means to flatten in column-major
    order if `a` is Fortran *contiguous* in memory,
    row-major order otherwise. 'K' means to flatten
    `a` in the order the elements occur in memory.
    The default is 'C'.

Returns
-------
y : ndarray
    A copy of the input array, flattened to one dimension.

See Also
--------
ravel : Return a flattened array.
flat : A 1-D flat iterator over the array.

Examples
--------
>>> a = np.array([[1,2], [3,4]])
>>> a.flatten()
array([1, 2, 3, 4])
>>> a.flatten('F')
array([1, 3, 2, 4])
Type:      builtin_function_or_method